local function update_score_text(self)
	gui.set_text(gui.get_node("score"), tostring(self.game_data.score))
end

local function update_status_text(text, ...)
	gui.set_text(gui.get_node("status"), string.format(text, ...))
end

local function on_data_loaded(self, data, error)
	if error then
		update_status_text("Unable to load data: %s", error)
	else
		self.game_data = sys.deserialize(data)
		self.game_data.score = math.floor(self.game_data.score or 0)
		update_status_text("Loaded data")
		update_score_text(self)
	end
end

local function on_data_saved(self, success, error)
	if success then
		update_status_text("Data saved")
	else
		update_status_text("Unable to save data: %s", error)
	end
end

local function on_audio_enabled_change(self, is_audio_enabled)
	update_status_text("Audio enabled: %s", is_audio_enabled and "yes" or "no")
end

local function on_pause(self)
	update_status_text("YouTube paused the game")
end

local function on_resume(self)
	update_status_text("YouTube resumed the game")
end

local function on_language(self, language, error)
	if error then
		update_status_text("Unable to get language: %s", error)
	else
		update_status_text("YouTube language: %s", language)
	end
end

local function on_score_sent(self, success, error)
	if success then
		update_status_text("Score sent")
	else
		update_status_text("Unable to send score: %s", error)
	end
end

local function on_content_opened(self, success, error)
	if success then
		update_status_text("Open-content request succeeded")
	else
		update_status_text("Unable to open content: %s", error)
	end
end

local function on_interstitial_ad(self, success, error)
	if success then
		update_status_text("Interstitial ad request succeeded")
	else
		update_status_text("Unable to request interstitial ad: %s", error)
	end
end

local function on_rewarded_ad(self, reward_earned, error)
	if error then
		update_status_text("Unable to request rewarded ad: %s", error)
	elseif reward_earned then
		update_status_text("Reward earned")
		-- Grant the reward here.
	else
		update_status_text("No reward earned")
	end
end

local function button(id, x, y)
	local node = gui.get_node(id .. "/button")
	return gui.pick_node(node, x, y)
end

function init(self)
	msg.post(".", "acquire_input_focus")
	sound.play("#sound")

	self.game_data = {
		score = 0
	}
	update_score_text(self)
	if html5 then
		playables.game_ready()
		update_status_text("YouTube Playables extension loaded")
		gui.set_text(gui.get_node("version"), tostring(playables.get_sdk_version()))
		print("In Playables environment:", playables.is_in_playables_env())
		on_audio_enabled_change(self, playables.is_audio_enabled())
		playables.on_audio_enabled_change(on_audio_enabled_change)
		playables.on_pause(on_pause)
		playables.on_resume(on_resume)
		playables.get_language(on_language)
	end
end

function on_input(self, action_id, action)
	if not html5 then
		return
	end

	if action_id == hash("touch") and action.released then
		self.game_data.score = self.game_data.score + 1
		update_score_text(self)
		if button("send_score", action.x, action.y) then
			playables.send_score(self.game_data.score, on_score_sent)
		elseif button("request_interstitial_ad", action.x, action.y) then
			playables.request_interstitial_ad(on_interstitial_ad)
		elseif button("request_rewarded_ad", action.x, action.y) then
			local reward_id = "foo"
			playables.request_rewarded_ad(reward_id, on_rewarded_ad)
		elseif button("save_data", action.x, action.y) then
			update_status_text("Saving data")
			local data = sys.serialize(self.game_data)
			playables.save_data(data, on_data_saved)
		elseif button("load_data", action.x, action.y) then
			update_status_text("Loading data")
			playables.load_data(on_data_loaded)
		end
		--playables.open_yt_content(message.id, playables.CONTENT_TYPE_VIDEO, on_content_opened)
		--playables.open_yt_content(message.id, playables.CONTENT_TYPE_PLAYABLE, on_content_opened)
		--playables.log_error()
		--playables.log_warning()
	end
end
