local function on_data_loaded(self, data, error)
	if error then
		print("Unable to load data:", error)
	else
		self.game_data = sys.deserialize(data)
		print("Loaded data:")
		pprint(self.game_data)
	end
end

local function on_data_saved(self, success, error)
	if success then
		print("Data saved")
	else
		print("Unable to save data:", error)
	end
end

local function on_audio_enabled_change(self, is_audio_enabled)
	print("Audio enabled:", is_audio_enabled)
end

local function on_pause(self)
	print("YouTube paused the game")
end

local function on_resume(self)
	print("YouTube resumed the game")
end

local function on_language(self, language, error)
	if error then
		print("Unable to get language:", error)
	else
		print("YouTube language:", language)
	end
end

local function on_score_sent(self, success, error)
	if success then
		print("Score sent")
	else
		print("Unable to send score:", error)
	end
end

local function on_content_opened(self, success, error)
	if success then
		print("Open-content request succeeded")
	else
		print("Unable to open content:", error)
	end
end

local function on_interstitial_ad(self, success, error)
	if success then
		print("Interstitial ad request succeeded")
	else
		print("Unable to request interstitial ad:", error)
	end
end

local function on_rewarded_ad(self, reward_earned, error)
	if error then
		print("Unable to request rewarded ad:", error)
	elseif reward_earned then
		print("Reward earned")
		-- Grant the reward here.
	else
		print("No reward earned")
	end
end

local function button(id, x, y)
	local node = gui.get_node(id .. "/button")
	return gui.pick_node(node, x, y)
end

function init(self)
	msg.post(".", "acquire_input_focus")
	sound.play("#sound")

	self.game_data = {
		clicks = 0,
		time = 0
	}
	if html5 then
		playables.game_ready()
		print("YouTube Playables extension loaded")
		print("In Playables environment:", playables.is_in_playables_env())
		print("YouTube Playables SDK version:", playables.get_sdk_version())
		on_audio_enabled_change(self, playables.is_audio_enabled())
		playables.on_audio_enabled_change(on_audio_enabled_change)
		playables.on_pause(on_pause)
		playables.on_resume(on_resume)
		playables.get_language(on_language)
	end
end

function on_input(self, action_id, action)
	if not html5 then
		return
	end

	if action_id == hash("touch") and action.released then
		self.game_data.clicks = self.game_data.clicks + 1
		self.game_data.time = os.time()
		if button("send_score", action.x, action.y) then
			playables.send_score(math.random(1, 1000), on_score_sent)
		elseif button("request_interstitial_ad", action.x, action.y) then
			playables.request_interstitial_ad(on_interstitial_ad)
		elseif button("request_rewarded_ad", action.x, action.y) then
			local reward_id = "foo"
			playables.request_rewarded_ad(reward_id, on_rewarded_ad)
		elseif button("save_data", action.x, action.y) then
			print("Saving data:")
			pprint(self.game_data)
			local data = sys.serialize(self.game_data)
			playables.save_data(data, on_data_saved)
		elseif button("load_data", action.x, action.y) then
			playables.load_data(on_data_loaded)
		end
		--playables.open_yt_content(message.id, playables.CONTENT_TYPE_VIDEO, on_content_opened)
		--playables.open_yt_content(message.id, playables.CONTENT_TYPE_PLAYABLE, on_content_opened)
		--playables.log_error()
		--playables.log_warning()
	end
end
